/*
 * Copyright (c) 2022-2026 Datalayer, Inc.
 *
 * Datalayer License
 */

export const DATALAYER_SVG_GALLERY = [
  'SvgJupyterEmbed',
  'SvgAgentRuntimes',
  'SvgVSCodeExtension',
  'SvgBlogHero',
  'SvgPricingHero',
  'SvgContactHero',
  'SvgAgentsHomeHero',
  'SvgLoginHero',
  'SvgUsecasesHero',
  'SvgIntegrationsHero',
  'SvgPartnersHero',
  'SvgChangelogHero',
  'SvgAboutHero',
  'SvgCareersHero',
  'SvgCommunityHero',
  'SvgJoin',
  'SvgJoinConfirm',
  'SvgInvites',
  'SvgDiscord',
  'SvgTutorialsHero',
  'SvgResearchHero',
  'SvgEvalsHero',
  'SvgEventsHero',
  'SvgStarsHero',
  'SvgSpitfire',
  'SvgBlackSnake',
  'SvgLinesLogo',
  'SvgOrganizationsAtScale',
  'SvgIndividualsAndTeams',
  'SvgAgentsHero',
  'SvgEarthHero',
  'SvgFastA2ADonation',
  'SvgRadar',
  'SvgNotebookArtifact',
  'SvgDocumentArtifact',
  'SvgCellArtifact',
  'SvgLessonArtifact',
  'SvgExerciseArtifact',
  'SvgAssignmentArtifact',
  'SvgDataset',
  'SvgJupyterMcp',
  'SvgLines',
  'SvgPublication',
  'SvgPixel1',
  'SvgPixel2',
  'SvgPrivacyHero',
  'SvgTermsHero',
  'SvgNotFound',
  'SvgUnauthorized',
  'SvgAI2',
] as const;

export type DatalayerSvgGalleryName = (typeof DATALAYER_SVG_GALLERY)[number];
